spring.application.name=26-Student-Management
server.port=8081

spring.datasource.url= jdbc:postgresql://localhost:5432/student_app
spring.datasource.username=postgres
spring.datasource.password=Root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/WEB-INF/views/